# action.yaml
name: 'Upload File to Sharepoint'
description: 'Upload one or more files in a directory to Sharepoint site using client ID'
inputs:
  file_path:
    description: 'Source file path (glob ok)'
    required: true
  site_name:
    description: 'Sharepoint site name (see README.md)'
    required: true
  host_name:
    description: 'Sharepoint host name (see README.md)'
    required: true
  upload_path:
    description: 'Target upload path (see README.md)'
    required: true
  sharepoint_token:
    description: 'Sharepoint token'
    required: true
  max_retries:
    description: 'Max retries for upload'
    required: false
    default: 3
outputs:
  return:
    description: 'Function output'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.send-file.outputs.return }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.site_name }}
    - ${{ inputs.host_name }}
    - ${{ inputs.upload_path }}
    - ${{ inputs.file_path }}
    - ${{ inputs.sharepoint_token }}
    - ${{ inputs.max_retries }}
