name: Update Major Release Tag

on:
  release:
    types: [created]

jobs:
  movetag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: fregante/setup-git-user@v2 # just the @actions user

    - name: Get major version num and update tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        MAJOR=${VERSION%%.*}
        git tag -fa "${MAJOR}" -m 'Update major version tag'
        git push origin "${MAJOR}" --force